name: maimaimai
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  barcode_scan2:
  camera:
  get:
  objectbox:
  path:
  path_provider:

  cupertino_icons: ^1.0.2
  objectbox_flutter_libs: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  objectbox_generator: any

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/msyh.ttf

  fonts:
    - family: Microsoft YaHei
      fonts:
        - asset: assets/fonts/msyh.ttf
